name: habitr
description: Habit-tracking social network built with Amplify Flutter
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  amplify_analytics_pinpoint:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/analytics/amplify_analytics_pinpoint
  amplify_api:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/api/amplify_api
  amplify_auth_cognito:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito
  amplify_flutter:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify/amplify_flutter
  amplify_storage_s3:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/storage/amplify_storage_s3
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  date_format: ^2.0.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  gql: ^0.14.0
  gql_exec: ^0.4.1
  gql_http_link: ^0.4.4
  habitr_models:
    path: models
  image_picker: ^0.8.0
  infinite_scroll_pagination: ^3.0.1+1
  json_annotation: ^4.7.0
  meta: ^1.8.0
  provider: ^6.0.2
  shared_preferences: ^2.0.6
  stream_transform: ^2.0.0
  tuple: ^2.0.0
  uuid: ^3.0.4

dependency_overrides:
  amplify_analytics_pinpoint:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/analytics/amplify_analytics_pinpoint
  amplify_analytics_pinpoint_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/analytics/amplify_analytics_pinpoint_dart
  amplify_api:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/api/amplify_api
  amplify_api_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/api/amplify_api_android
  amplify_api_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/api/amplify_api_ios
  amplify_auth_cognito:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito
  amplify_auth_cognito_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito_android
  amplify_auth_cognito_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito_dart
  amplify_auth_cognito_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/auth/amplify_auth_cognito_ios
  amplify_core:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify_core
  amplify_flutter:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify/amplify_flutter
  amplify_flutter_android:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify/amplify_flutter_android
  amplify_flutter_ios:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/amplify/amplify_flutter_ios
  amplify_secure_storage:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/secure_storage/amplify_secure_storage
  amplify_secure_storage_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/secure_storage/amplify_secure_storage_dart
  amplify_storage_s3:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/storage/amplify_storage_s3
  amplify_storage_s3_dart:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/storage/amplify_storage_s3_dart
  aws_common:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/aws_common
  aws_signature_v4:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/aws_signature_v4
  smithy:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/smithy/smithy
  smithy_aws:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/smithy/smithy_aws
  worker_bee:
    git:
      url: https://github.com/aws-amplify/amplify-flutter.git
      ref: non_auth_pentest
      path: packages/worker_bee/worker_bee

dev_dependencies:
  amplify_lints: ^2.0.1
  args: ^2.1.1
  build_runner: ^2.0.4
  flutter_lorem: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
