name: habitr
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  amplify_analytics_pinpoint:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_analytics_pinpoint
  amplify_auth_cognito:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_auth_cognito
  amplify_api:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_api
  amplify_flutter:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_flutter
  amplify_storage_s3:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_storage_s3
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  google_fonts: ^2.1.0
  gql: ^0.13.0
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0
  habitr_models:
    path: models
  image_picker: ^0.8.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  stream_transform: ^2.0.0
  tuple: ^2.0.0
  infinite_scroll_pagination: ^3.0.1+1

dependency_overrides:
  json_annotation: ^4.0.1
  amplify_api_plugin_interface:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_api_plugin_interface
  amplify_analytics_plugin_interface:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_analytics_plugin_interface
  amplify_auth_plugin_interface:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_auth_plugin_interface
  amplify_core:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_core
  amplify_datastore_plugin_interface:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_datastore_plugin_interface
  amplify_storage_plugin_interface:
    git:
      url: https://github.com/aws-amplify/amplify-flutter
      ref: null-safety-master
      path: packages/amplify_storage_plugin_interface

dev_dependencies:
  args: ^2.1.1
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_lorem: ^2.0.0
  json_serializable: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
