name: create_user
description: A web server built using the shelf package.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  habitr_models:
    path: ../../models
  aws_lambda_dart_runtime:
    git: 
      url: https://github.com/dnys1/aws-lambda-dart-runtime.git
      ref: upgrade
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0

dependency_overrides:
  json_annotation: ^4.0.0

dev_dependencies:
  pedantic: ^1.10.0
  build_runner: ^2.0.0
