name: Deploy
on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: us-west-2
  AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
  AMPLIFY_ENV_NAME: dev

jobs:
  build:
    name: Build (Android)
    runs-on: ubuntu-latest

    # Required for AWS credentials action
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          # Preferred version for Amplify CLI
          node-version: '14'
      - name: Setup Amplify
        # Instead of running `npm install -g @aws-amplify/cli`, download
        # the pre-compiled version to speed up build.
        run: |
          AMPLIFY_VERSION=$(npm show @aws-amplify/cli version)
          curl -L -o amplify.tgz https://github.com/aws-amplify/amplify-cli/releases/download/v${AMPLIFY_VERSION}/amplify-pkg-linux.tgz
          tar -xzf amplify.tgz
          chmod +x amplify-pkg-linux
          mv amplify-pkg-linux /usr/local/bin/amplify
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AMPLIFY_ROLE_ARN }}
          role-session-name: habitr-build
          aws-region: ${{ env.AWS_REGION }}
      - name: Pull Amplify project
        run: script/pull.sh
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
        # Optional. Speeds up `flutter pub get` by saving the local
        # pub cache in between builds.
      - name: Cache Flutter packages
        uses: actions/cache@v2
        env:
          cache-name: pub-cache
        with:
          # These variables are set by subosito/flutter-action.
          path: |
            $PUB_CACHE
            $FLUTTER_ROOT/.pub-cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter build apk --debug
