name: Deploy
on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: us-west-2
  AMPLIFY_APP_ID: ${{ secrets.AMPLIFY_APP_ID }}
  AMPLIFY_ENV_NAME: dev

jobs:
  build:
    name: Build (Android)
    runs-on: ubuntu-latest

    # Required for AWS credentials action
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          # Preferred version for Amplify CLI
          node-version: '14'
      - name: Setup Amplify
        run: npm install -g @aws-amplify/cli
      - name: Setup AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AMPLIFY_ROLE_ARN }}
          role-session-name: habitr-build
          aws-region: ${{ env.AWS_REGION }}
      - name: Pull Amplify project
        run: script/pull.sh
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
        # Optional. Speeds up `flutter pub get` by saving the local
        # pub cache in between builds.
      - name: Cache Flutter packages
        uses: actions/cache@v2
        env:
          cache-name: pub-cache
        with:
          path: |
            ~/.pub-cache
            $FLUTTER_HOME/.pub-cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-
            ${{ runner.os }}-
      - run: flutter config --no-analytics
      - run: flutter pub get
      - run: flutter build apk --debug
