name: habitr_models
description: Common models for Habitr and its server-side functions.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  gql: ^0.13.1-0
  gql_code_builder: ^0.5.0
  json_annotation: ^4.4.0

dev_dependencies:
  amplify_lints: ^1.0.0
  build_runner: ^2.0.4
  gql_build: ^0.4.1-0
  json_serializable: ^6.1.0
  test: ^1.16.0
