name: habitr_models
description: Common models for Habitr and its server-side functions.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  gql: ^0.13.0
  gql_code_builder: ^0.2.0
  json_annotation: ^4.0.1

dependency_overrides:
  json_annotation: ^4.0.1

dev_dependencies:
  build_runner: ^2.0.4
  gql_build: ^0.2.0
  json_serializable: ^4.1.3
  pedantic: ^1.10.0
  test: ^1.16.0
